openapi: 3.0.3
info:
  title: SupplyChainAlerts API
  version: 1.0.0
  description: Real-time supply chain disruption alerts
servers:
  - url: https://api.example.com
paths:
  /v1/health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /v1/alerts:
    get:
      summary: List alerts
      parameters:
        - in: query
          name: region
          schema: { type: string }
        - in: query
          name: country
          schema: { type: string }
        - in: query
          name: type
          schema: { type: string, description: Disruption type }
        - in: query
          name: severity
          schema: { type: string, enum: [low, medium, high] }
        - in: query
          name: since
          schema: { type: string, format: date-time }
        - in: query
          name: limit
          schema: { type: integer, minimum: 1, maximum: 500 }
      responses:
        '200':
          description: Alerts
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Alert'
                  count:
                    type: integer
components:
  schemas:
    Alert:
      type: object
      properties:
        id: { type: string }
        source: { type: string }
        title: { type: string }
        summary: { type: string }
        url: { type: string, format: uri }
        detected_at: { type: string, format: date-time }
        published_at: { type: string, format: date-time }
        region: { type: string }
        country: { type: string }
        location: { type: string }
        latitude: { type: number, format: double }
        longitude: { type: number, format: double }
        disruption: { type: string }
        severity: { type: string, enum: [low, medium, high] }
        sentiment: { type: string, enum: [negative, neutral, positive] }
        confidence: { type: number, format: double }

